default_platform(:android)

platform :android do
  lane :beta do
    current_build_number = google_play_track_version_codes(
      track: "internal",
    )[0]

    Dir.chdir("../..") do
      sh "echo $PLAY_STORE_UPLOAD_KEYSTORE | base64 -d > android/keystore.jks"
      sh "flutter build appbundle --build-number=#{current_build_number + 1}"
    end

    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
      release_status: "draft",
    )
  end
end
