default_platform(:android)

platform :android do
  lane :build do
    latest_release = firebase_app_distribution_get_latest_release(
      service_credentials_json_data: ENV["GOOGLE_SERVICE_ACCOUNT"],
      app: "1:58678861052:android:a1ecff4792b696f9bd8b79",
    )
    target_build_number = latest_release[:buildVersion].to_i + 1

    Dir.chdir("../..") do
      sh "echo $PLAY_STORE_UPLOAD_KEYSTORE | base64 -d > android/keystore.jks"
      sh "flutter build apk --build-number=#{target_build_number} --dart-define=ENV=release"
    end

    dist = firebase_app_distribution(
      service_credentials_json_data: ENV["GOOGLE_SERVICE_ACCOUNT"],
      app: "1:58678861052:android:a1ecff4792b696f9bd8b79",
      groups: "android@team",
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
    )

    slack(
      slack_url: ENV["SLACK_WEBHOOK_URL"],
      channel: '#activities',
      pretext: "새 테스트 빌드가 있습니다 :rocket:",
      default_payloads: [],
      use_webhook_configured_username_and_icon: true,
      attachment_properties: {
        fields: [
          { title: "플랫폼", value: "Android", short: true },
          { title: "빌드", value: "#{dist[:displayVersion]} (#{dist[:buildVersion]})", short: true },
          { title: "릴리즈 페이지", value: dist[:testingUri] },
        ],
      },
    )
  end

  lane :beta do
    dist = firebase_app_distribution(
      service_credentials_json_data: ENV["GOOGLE_SERVICE_ACCOUNT"],
      app: "1:58678861052:android:a1ecff4792b696f9bd8b79",
      groups: "android@team, android@beta",
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
    )

    slack(
      slack_url: ENV["SLACK_WEBHOOK_URL"],
      channel: '#app-private-beta',
      pretext: "새 베타 빌드가 있습니다 :rocket:",
      default_payloads: [],
      use_webhook_configured_username_and_icon: true,
      attachment_properties: {
        fields: [
          { title: "플랫폼", value: "Android", short: true },
          { title: "빌드", value: "#{dist[:displayVersion]} (#{dist[:buildVersion]})", short: true },
          { title: "릴리즈 페이지", value: dist[:testingUri] },
        ],
      },
    )
  end

  lane :release do
    latest_release = firebase_app_distribution_get_latest_release(
      service_credentials_json_data: ENV["GOOGLE_SERVICE_ACCOUNT"],
      app: "1:58678861052:android:a1ecff4792b696f9bd8b79",
    )
    target_build_number = latest_release[:buildVersion].to_i

    Dir.chdir("../..") do
      sh "echo $PLAY_STORE_UPLOAD_KEYSTORE | base64 -d > android/keystore.jks"
      sh "flutter build appbundle --build-number=#{target_build_number} --dart-define=ENV=release"
    end

    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      sync_image_upload: true,
    )
  end
end
