export const UNAVAILABLE_SPACE_SLUGS = {
  EXACT: [
    // route urls
    '_internal',
    '_playground',
    'api',
    'login',
    'me',
    'search',
    'signup',

    // static urls
    '_app',
    'favicon.ico',
    'icons',
    'robots.txt',
    'sitemap.xml',

    // reserved keywords
    'account',
    'accounts',
    'admin',
    'announcement',
    'announcements',
    'article',
    'articles',
    'blog',
    'blogs',
    'event',
    'events',
    'help',
    'image',
    'images',
    'legal',
    'logout',
    'member',
    'members',
    'membership',
    'memberships',
    'notice',
    'notices',
    'new',
    'news',
    'official',
    'officials',
    'post',
    'posts',
    'profile',
    'profiles',
    'space',
    'spaces',
    'story',
    'stories',
    'support',
    'supports',
    'team',
    'teams',
    'user',
    'users',
  ],

  CONTAIN: ['penxle'],
};
