runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: latest

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm

    - run: pnpm install --frozen-lockfile
      shell: bash

    - run: pnpm run build:actions
      shell: bash
