import 'package:glyph/emojis/data.dart';
import 'package:glyph/emojis/emoji.dart';

class EmojiSubsetSection {
  const EmojiSubsetSection({required this.name, required this.emojis});

  final String name;
  final List<EmojiData> emojis;
}

abstract final class EmojiSubsets {
  static const sections = <EmojiSubsetSection>[
    EmojiSubsetSection(
      name: '인기',
      emojis: [
        Emojis.heart,
        Emojis.thumbs_up,
        Emojis.heart_eyes,
        Emojis.n100,
        Emojis.sob,
        Emojis.face_holding_back_tears,
        Emojis.heart_on_fire,
        Emojis.sparkling_heart,
        Emojis.clap,
        Emojis.smiling_face_with_3_hearts,
        Emojis.heartpulse,
        Emojis.cupid,
        Emojis.kissing_heart,
        Emojis.two_hearts,
        Emojis.revolving_hearts,
        Emojis.face_with_peeking_eye,
        Emojis.blue_heart,
        Emojis.innocent,
        Emojis.flushed,
        Emojis.grinning,
        Emojis.gift_heart,
        Emojis.kiss,
        Emojis.laughing,
        Emojis.heart_eyes_cat,
        Emojis.star_struck,
        Emojis.fire,
      ],
    ),
    EmojiSubsetSection(
      name: '표정 및 인물',
      emojis: [
        Emojis.n100,
        Emojis.grinning,
        Emojis.smile,
        Emojis.laughing,
        Emojis.rolling_on_the_floor_laughing,
        Emojis.wink,
        Emojis.blush,
        Emojis.innocent,
        Emojis.smiling_face_with_3_hearts,
        Emojis.heart_eyes,
        Emojis.star_struck,
        Emojis.kissing_heart,
        Emojis.face_with_hand_over_mouth,
        Emojis.face_with_peeking_eye,
        Emojis.flushed,
        Emojis.face_holding_back_tears,
        Emojis.sob,
        Emojis.heart_eyes_cat,
        Emojis.kiss,
        Emojis.love_letter,
        Emojis.cupid,
        Emojis.gift_heart,
        Emojis.sparkling_heart,
        Emojis.heartpulse,
        Emojis.revolving_hearts,
        Emojis.two_hearts,
        Emojis.heart_on_fire,
        Emojis.heart,
        Emojis.orange_heart,
        Emojis.yellow_heart,
        Emojis.green_heart,
        Emojis.blue_heart,
        Emojis.purple_heart,
        Emojis.brown_heart,
        Emojis.black_heart,
        Emojis.white_heart,
        Emojis.dizzy,
        Emojis.sweat_drops,
        Emojis.thumbs_up,
        Emojis.clap,
        Emojis.raised_hands,
      ],
    ),
    EmojiSubsetSection(
      name: '자연',
      emojis: [
        Emojis.cat,
        Emojis.hamster,
        Emojis.rabbit,
        Emojis.bear,
        Emojis.polar_bear,
        Emojis.feet,
        Emojis.hatching_chick,
        Emojis.butterfly,
        Emojis.cherry_blossom,
        Emojis.blossom,
        Emojis.seedling,
        Emojis.herb,
        Emojis.four_leaf_clover,
      ],
    ),
    EmojiSubsetSection(
      name: '음식',
      emojis: [
        Emojis.grapes,
        Emojis.melon,
        Emojis.watermelon,
        Emojis.tangerine,
        Emojis.lemon,
        Emojis.banana,
        Emojis.apple,
        Emojis.green_apple,
        Emojis.peach,
        Emojis.cherries,
        Emojis.strawberry,
        Emojis.eggplant,
        Emojis.popcorn,
        Emojis.cookie,
        Emojis.birthday,
        Emojis.chocolate_bar,
      ],
    ),
    EmojiSubsetSection(
      name: '기타',
      emojis: [
        Emojis.rocket,
        Emojis.full_moon,
        Emojis.star,
        Emojis.star2,
        Emojis.rainbow,
        Emojis.fire,
        Emojis.jack_o_lantern,
        Emojis.christmas_tree,
        Emojis.sparkles,
        Emojis.gift,
        Emojis.frame_with_picture,
        Emojis.art,
        Emojis.thread,
        Emojis.pencil2,
      ],
    ),
  ];
}
